# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
        args:
            - --enable=F,E,W,C,R
            - --max-line-length=120
            - --variable-naming-style=any
            - --const-naming-style=any
            - --argument-naming-style=any
            - --ignore-long-lines=^\s*(#\s*)?<?https?://\S+>?$
            # - --disable=C,R,E0401
            - --disable=C0301

-   repo: local
    hooks:
    -   id: system
        name: verible-verilog-format
        entry: verible-verilog-format
        language: system
        files: \.sv$
        args:
            - --inplace

-   repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
    -   id: isort
