[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
